//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.IO;
using System.Resources;
using System.Runtime.CompilerServices;

namespace AstroSoundBoard.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("AstroSoundBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream A_LOT_OF_CUNTS {
            get {
                return ResourceManager.GetStream("A_LOT_OF_CUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream AGAINST_ME {
            get {
                return ResourceManager.GetStream("AGAINST_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream AMEIZING {
            get {
                return ResourceManager.GetStream("AMEIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream ANY_INDICATION {
            get {
                return ResourceManager.GetStream("ANY_INDICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream ASTROCITY {
            get {
                return ResourceManager.GetStream("ASTROCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/TheAstroKitty.
        /// </summary>
        internal static string AstroSocial_Facebook {
            get {
                return ResourceManager.GetString("AstroSocial_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.twitch.tv/astrokittylive.
        /// </summary>
        internal static string AstroSocial_Twitch {
            get {
                return ResourceManager.GetString("AstroSocial_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/astrokitty.
        /// </summary>
        internal static string AstroSocial_Twitter {
            get {
                return ResourceManager.GetString("AstroSocial_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/user/TheAstronautKitty.
        /// </summary>
        internal static string AstroSocial_Youtube {
            get {
                return ResourceManager.GetString("AstroSocial_Youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream AW_YEAH_PAPI {
            get {
                return ResourceManager.GetStream("AW_YEAH_PAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream BABY_TO_HELP_YOU {
            get {
                return ResourceManager.GetStream("BABY_TO_HELP_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream BAD_DECISIONS {
            get {
                return ResourceManager.GetStream("BAD_DECISIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream BEST_DAY_FOR_MONKEY {
            get {
                return ResourceManager.GetStream("BEST_DAY_FOR_MONKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream BLUE_GUNG {
            get {
                return ResourceManager.GetStream("BLUE_GUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream BOOPEY_BOOPEY {
            get {
                return ResourceManager.GetStream("BOOPEY_BOOPEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream BOOPI_BOOPI_2 {
            get {
                return ResourceManager.GetStream("BOOPI_BOOPI_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream BYE_BYE {
            get {
                return ResourceManager.GetStream("BYE_BYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream CALCULATED {
            get {
                return ResourceManager.GetStream("CALCULATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream CAVELERY_IS_HERE {
            get {
                return ResourceManager.GetStream("CAVELERY_IS_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream CHEEKY_BOOP {
            get {
                return ResourceManager.GetStream("CHEEKY_BOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream CHEEKY_CHEEKY {
            get {
                return ResourceManager.GetStream("CHEEKY_CHEEKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream CRYING_OATS {
            get {
                return ResourceManager.GetStream("CRYING_OATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream CRYING_SCARY {
            get {
                return ResourceManager.GetStream("CRYING_SCARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream CUM_HERE_BITCH {
            get {
                return ResourceManager.GetStream("CUM_HERE_BITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DARKNESS_IM_DAD {
            get {
                return ResourceManager.GetStream("DARKNESS_IM_DAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DICK_ON_POINT {
            get {
                return ResourceManager.GetStream("DICK_ON_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DICK_SKIN_IS_PEELING {
            get {
                return ResourceManager.GetStream("DICK_SKIN_IS_PEELING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DINKI {
            get {
                return ResourceManager.GetStream("DINKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DO_IT_FOR_THE_MEMEZ {
            get {
                return ResourceManager.GetStream("DO_IT_FOR_THE_MEMEZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DOES_HAVE_CANCER {
            get {
                return ResourceManager.GetStream("DOES_HAVE_CANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DONT_DO_IT {
            get {
                return ResourceManager.GetStream("DONT_DO_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DONT_HURT_ME {
            get {
                return ResourceManager.GetStream("DONT_HURT_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DROP_THAT_CHITTY {
            get {
                return ResourceManager.GetStream("DROP_THAT_CHITTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream DVA_THAT_MOMENT {
            get {
                return ResourceManager.GetStream("DVA_THAT_MOMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream EJECT_IF_SEX {
            get {
                return ResourceManager.GetStream("EJECT_IF_SEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream ENGINE_START {
            get {
                return ResourceManager.GetStream("ENGINE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream EXCELENT_SHATTER {
            get {
                return ResourceManager.GetStream("EXCELENT_SHATTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream EXCELLENTE_AMIGOS {
            get {
                return ResourceManager.GetStream("EXCELLENTE_AMIGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream FOCK_OFF {
            get {
                return ResourceManager.GetStream("FOCK_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream FUCKING_DOMINATE {
            get {
                return ResourceManager.GetStream("FUCKING_DOMINATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream FUCKING_JUNKRAT {
            get {
                return ResourceManager.GetStream("FUCKING_JUNKRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream FUCKING_MERCY {
            get {
                return ResourceManager.GetStream("FUCKING_MERCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream FUCKING_NEOW {
            get {
                return ResourceManager.GetStream("FUCKING_NEOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream GET_HER_BABY {
            get {
                return ResourceManager.GetStream("GET_HER_BABY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream GIVE_A_BLOWJOB {
            get {
                return ResourceManager.GetStream("GIVE_A_BLOWJOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream GIVE_IT_TO_ME_ASTRO {
            get {
                return ResourceManager.GetStream("GIVE_IT_TO_ME_ASTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream GOING_TOO_DEEP_GUYS {
            get {
                return ResourceManager.GetStream("GOING_TOO_DEEP_GUYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream GOLD_ELIMS {
            get {
                return ResourceManager.GetStream("GOLD_ELIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream GOOD_CATCH {
            get {
                return ResourceManager.GetStream("GOOD_CATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream GUNG {
            get {
                return ResourceManager.GetStream("GUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream HARMONY_ORB {
            get {
                return ResourceManager.GetStream("HARMONY_ORB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream HE_CAME_IN_MY_FACE {
            get {
                return ResourceManager.GetStream("HE_CAME_IN_MY_FACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream HEAL_ME_YOU_CUNT {
            get {
                return ResourceManager.GetStream("HEAL_ME_YOU_CUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream HEY {
            get {
                return ResourceManager.GetStream("HEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream HEY_FAM {
            get {
                return ResourceManager.GetStream("HEY_FAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream HIT_ME {
            get {
                return ResourceManager.GetStream("HIT_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream HOW_TO_THROW {
            get {
                return ResourceManager.GetStream("HOW_TO_THROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream I_AM_NUTCRACKER {
            get {
                return ResourceManager.GetStream("I_AM_NUTCRACKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream I_MAIN_CANCER {
            get {
                return ResourceManager.GetStream("I_MAIN_CANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream I_WANT_TO_DIE {
            get {
                return ResourceManager.GetStream("I_WANT_TO_DIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream IDIOT_LUCIO {
            get {
                return ResourceManager.GetStream("IDIOT_LUCIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream INTENSE_GAMEPLAY {
            get {
                return ResourceManager.GetStream("INTENSE_GAMEPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream INTO_HER_ASSHOLE {
            get {
                return ResourceManager.GetStream("INTO_HER_ASSHOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream IS_THIS_HARAMBE {
            get {
                return ResourceManager.GetStream("IS_THIS_HARAMBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream JUST_WALK_OVER {
            get {
                return ResourceManager.GetStream("JUST_WALK_OVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream LOVE_SUICIDE {
            get {
                return ResourceManager.GetStream("LOVE_SUICIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream MAINHART_RAIN {
            get {
                return ResourceManager.GetStream("MAINHART_RAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream MONKEY_EAT_MY_ASS {
            get {
                return ResourceManager.GetStream("MONKEY_EAT_MY_ASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream MONKEY_MONKEY {
            get {
                return ResourceManager.GetStream("MONKEY_MONKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream MONKEY_ON_ME {
            get {
                return ResourceManager.GetStream("MONKEY_ON_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream MORE_STYLE {
            get {
                return ResourceManager.GetStream("MORE_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream MOVED_ASLEEP {
            get {
                return ResourceManager.GetStream("MOVED_ASLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream NICE_BOOP {
            get {
                return ResourceManager.GetStream("NICE_BOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream NICE_JOB_ASTRO {
            get {
                return ResourceManager.GetStream("NICE_JOB_ASTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream NICE_JOB_MEN {
            get {
                return ResourceManager.GetStream("NICE_JOB_MEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream NICE_PHARA {
            get {
                return ResourceManager.GetStream("NICE_PHARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream NO_HOMO {
            get {
                return ResourceManager.GetStream("NO_HOMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream NO_NO_NO_NO {
            get {
                return ResourceManager.GetStream("NO_NO_NO_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream NOT_EXPECT_MUCH {
            get {
                return ResourceManager.GetStream("NOT_EXPECT_MUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream NOT_PAST_GORILLA {
            get {
                return ResourceManager.GetStream("NOT_PAST_GORILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream OH_HELLO {
            get {
                return ResourceManager.GetStream("OH_HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream ON_THE_SIGHT {
            get {
                return ResourceManager.GetStream("ON_THE_SIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream ONE_KILL_CARRY {
            get {
                return ResourceManager.GetStream("ONE_KILL_CARRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream OVERUSED_MEME {
            get {
                return ResourceManager.GetStream("OVERUSED_MEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream PHARA_VS_SOLIDER {
            get {
                return ResourceManager.GetStream("PHARA_VS_SOLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream PLATNIUM_DAMAGE {
            get {
                return ResourceManager.GetStream("PLATNIUM_DAMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream PRETTY_GOOD_PUSH {
            get {
                return ResourceManager.GetStream("PRETTY_GOOD_PUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream PRETTY_NICE_BOOP {
            get {
                return ResourceManager.GetStream("PRETTY_NICE_BOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/FetzenRndy/AstroSoundboard.
        /// </summary>
        internal static string Project_Github {
            get {
                return ResourceManager.GetString("Project_Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream REZ_ME {
            get {
                return ResourceManager.GetStream("REZ_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream RIPPAAA {
            get {
                return ResourceManager.GetStream("RIPPAAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream RRRRRRR {
            get {
                return ResourceManager.GetStream("RRRRRRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream RUNAWAY_EFFECT {
            get {
                return ResourceManager.GetStream("RUNAWAY_EFFECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream RUNNAWAY_FROM_ME {
            get {
                return ResourceManager.GetStream("RUNNAWAY_FROM_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SHUT_UP_ASTROKITTY {
            get {
                return ResourceManager.GetStream("SHUT_UP_ASTROKITTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SICK_ULT {
            get {
                return ResourceManager.GetStream("SICK_ULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SLEEPY_BYE_BYE {
            get {
                return ResourceManager.GetStream("SLEEPY_BYE_BYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SMACK_BABYS {
            get {
                return ResourceManager.GetStream("SMACK_BABYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SMACK_MY_BITCH_UP {
            get {
                return ResourceManager.GetStream("SMACK_MY_BITCH_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SO_ERRECT {
            get {
                return ResourceManager.GetStream("SO_ERRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SO_RUDE {
            get {
                return ResourceManager.GetStream("SO_RUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;FileVersion&quot;: &quot;1&quot;,
        ///    &quot;ParserVersion&quot;: &quot;1&quot;,
        ///    &quot;Sounds&quot;: [{
        ///            &quot;sound&quot;: {
        ///                &quot;name&quot;: &quot;FUCKING_MERCY&quot;
        ///            },
        ///            &quot;info&quot;: {
        ///                &quot;VideoLink&quot;: &quot;https://www.youtube.com/embed/11olpkle_YQ&quot;,
        ///                &quot;Description&quot;: &quot;Friend of Astro Screaming &apos;FUCKING MERCY&apos; as a mercy comes in and revives alot of people and causing them to lose the Game. - Mercy OP please nerf&quot;
        ///            }
        ///        },
        ///        {
        ///            &quot;sound&quot;: {
        ///                &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoundDefinition {
            get {
                return ResourceManager.GetString("SoundDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream STOP_BEING_A_PUSSY {
            get {
                return ResourceManager.GetStream("STOP_BEING_A_PUSSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SUCK_MY_DICK {
            get {
                return ResourceManager.GetStream("SUCK_MY_DICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SUCK_MY_ORBS {
            get {
                return ResourceManager.GetStream("SUCK_MY_ORBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream SUICIDE {
            get {
                return ResourceManager.GetStream("SUICIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream THAT_SUCKS_DICK_DUDE {
            get {
                return ResourceManager.GetStream("THAT_SUCKS_DICK_DUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream THATS_ALRIGHT_BAE {
            get {
                return ResourceManager.GetStream("THATS_ALRIGHT_BAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream THATS_UNFORTUNATE {
            get {
                return ResourceManager.GetStream("THATS_UNFORTUNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream THE_META {
            get {
                return ResourceManager.GetStream("THE_META", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream THERE_IS_YOUR_PICK {
            get {
                return ResourceManager.GetStream("THERE_IS_YOUR_PICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream THIS_IS_A_BAD_IDEA {
            get {
                return ResourceManager.GetStream("THIS_IS_A_BAD_IDEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream THIS_MOMENT {
            get {
                return ResourceManager.GetStream("THIS_MOMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream TRUMP_2017 {
            get {
                return ResourceManager.GetStream("TRUMP_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream TURNED_INTO_TRACER {
            get {
                return ResourceManager.GetStream("TURNED_INTO_TRACER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream WAS_THAT_A_GRILL {
            get {
                return ResourceManager.GetStream("WAS_THAT_A_GRILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream WHAT_SHE_SAID {
            get {
                return ResourceManager.GetStream("WHAT_SHE_SAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream WHEN_YOU_TRY {
            get {
                return ResourceManager.GetStream("WHEN_YOU_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream WINSTON_BOOP {
            get {
                return ResourceManager.GetStream("WINSTON_BOOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream WINSTON_COCK_LONG {
            get {
                return ResourceManager.GetStream("WINSTON_COCK_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream WINSTON_ON_MY_COCK {
            get {
                return ResourceManager.GetStream("WINSTON_ON_MY_COCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream YOU_SLUT {
            get {
                return ResourceManager.GetStream("YOU_SLUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream YOU_SUCK_DUDE {
            get {
                return ResourceManager.GetStream("YOU_SUCK_DUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static UnmanagedMemoryStream YOUR_FUCKED {
            get {
                return ResourceManager.GetStream("YOUR_FUCKED", resourceCulture);
            }
        }
    }
}
